version: '3.5'

services:
  frontti:
    ports:
      - 5000:5000
    build: ../ex1.10
  backki:
    ports:
      - 8000:8000
    build: ../ex1.11
    environment:
      - REDIS=redis
  redis:
    image: redis
    ports:
      - 6379:6379
